### ISSUE TITLE
MacOS Support

### ISSUE THREAD

**Issue by MarZab** [ScR4tCh/timebox#6]
I was playing around with MacOS, hopefully this helps someone or me in the future.

```
git clone https://github.com/ScR4tCh/timebox.git
cd timebox
virtualenv env
source env/bin/activate
pip install pyobjc
pip install git+https://github.com/0-1-0/lightblue-0.4.git
pip install git+https://github.com/karulis/pybluez.git
pip install -r requirements.txt 
```

You'll need to change the source a bit:

```
    self.addr, _ = self.sock.getpeername()
```

to

```
	self.addr, _ = self.sock.getsockname()
```

Disconnect the timebox and make sure it's waiting for a pairing.

```
python timebox/timebox.py settime now
```

I got these errors randomly when installing/uninstalling lightblue and pybluez, I had to fiddle around installing/reinstalling them until it worked. 

- `AttributeError: 'module' object has no attribute 'setSignatureForSelector'` 
- `ImportError: Cannot load LightAquaBlue framework`:

At some point, this folder got created:

```
/env/lib/python2.7/site-packages/lightblue/LightAquaBlue.framework/
```

A popup will come up asking you to pair with the Timebox, meanwhile the script will error out so you need to kill the shell and start over.

```
cd timebox
source env/bin/activate
python timebox/timebox.py settime now
```

It will show a error, but it will work!

```
(env) MarkBookPro:timebox marko$ python timebox/timebox.py settime now
-checking device 11:75:58:D8:91:51
2018-04-17 10:44:25.455 python[2601:273300] [establishKernelConnection] Received an error from IOServiceOpen() - 0xe00002c7.  NULLing out io_service_t.
```

**Comment by leturtle** [comment]
You saved my day 👍

**Comment by leturtle** [comment]
After all, I use upstream https://github.com/pybluez/pybluez instead, in which`lightblue` is embed.

`pip install --no-cache-dir git+https://github.com/pybluez/pybluez.git`

Install without cache dir may help to resolve `Cannot load LightAquaBlue framework` issue. I think `bdist_wheel` prevent xcodebuild from building the project.

**Comment by limacohen** [comment]
For posterity, these are the extra steps I took to make it work in Mac OS 10.10.3:

1. Start as stated by op until (including) `pip install pyobjc`
2. Don't install `lightblue` since `pybluez` embeds its own version (and it's different)
3. (Make sure you have Xcode installed before the next step, not just the Command Line Tools)
4. Clone `https://github.com/pybluez/pybluez.git`, `open pybluez/macos/LightAquaBlue/LightAquaBlue.xcodeproj`,  [follow this steps in order to fix the "does not contain scheme" error](https://stackoverflow.com/a/16049998/38400), `cd` and `python setup.py install`
5. Finally install the requirements, edit `timebox/timebox.py` with the op fix and replace all `ord(c)` with just `c`

Alternatively, you can clone [MarcG046's fork](https://github.com/MarcG046/timebox) saving you the last step, and adding some functionality on top.

Three hours of "gotchas" later, I can now search and send gifs to my Timebox-mini directly from Alfred :')
![Worth it](https://duaw26jehqd4r.cloudfront.net/items/0d0a2L2T2w2d0H2z2n3c/Screen%20Shot%202018-12-17%20at%209.30.45%20PM.png)
